
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS=True
# EMAIL_HOST=env('DEVELOPMENT_EMAIL_HOST')
# EMAIL_HOST_USER=env('DEVELOPMENT_EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD=env('DEVELOPMENT_EMAIL_HOST_PASSWORD')
# EMAIL_PORT=env('DEVELOPMENT_EMAIL_PORT')